# Generated by Django 5.2.17 on 2026-10-01 22:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NEW_NEARBY_REQUEST", "Новий запит поруч"),
                            ("HELP_RESPONSE_RECEIVED", "Отримано відгук"),
                            ("HELP_RESPONSE_ACCEPTED", "Відгук прийнято"),
                            ("HELP_RESPONSE_REJECTED", "Відгук відхилено"),
                            ("NEW_MESSAGE", "Нове повідомлення"),
                            ("REQUEST_COMPLETED", "Запит завершено"),
                            ("THANK_YOU_RECEIVED", "Отримано подяку"),
                            ("REQUEST_EXPIRING", "Запит скоро завершиться"),
                            ("REQUEST_CANCELLED", "Запит скасовано"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.CharField(blank=True, max_length=500)),
                ("url", models.CharField(blank=True, max_length=255)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("dedupe_key", models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("push_sent_at", models.DateTimeField(blank=True, null=True)),
                ("push_opened_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "сповіщення",
                "verbose_name_plural": "сповіщення",
                "ordering": ["-created_at"],
            },
        ),
    ]
