# Generated by Django 5.2.17 on 2026-10-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="muted_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
