# Generated by Django 5.2.17 on 2026-10-01 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.city",
            ),
        ),
        migrations.AddConstraint(
            model_name="socialaccount",
            constraint=models.UniqueConstraint(fields=("provider", "uid"), name="unique_social_account"),
        ),
        migrations.AddConstraint(
            model_name="usercapability",
            constraint=models.UniqueConstraint(fields=("user", "capability"), name="unique_user_capability"),
        ),
    ]
