# Generated by Django 5.2.17 on 2026-10-02 13:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_seed_capabilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="custom_items",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=40), blank=True, default=list, size=None
            ),
        ),
    ]
