# Generated by Django 5.2.17 on 2026-10-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_always_show_name_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
