# Generated by Django 5.2.17 on 2026-10-01 22:33

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "розмова",
                "verbose_name_plural": "розмови",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "text",
                    models.TextField(
                        blank=True, max_length=3000, validators=[django.core.validators.MaxLengthValidator(3000)]
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("TEXT", "Текст"), ("IMAGE", "Зображення"), ("SYSTEM", "Системне")],
                        default="TEXT",
                        max_length=10,
                    ),
                ),
                ("client_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "повідомлення",
                "verbose_name_plural": "повідомлення",
                "ordering": ["-created_at"],
            },
        ),
    ]
