# Generated by Django 5.2.17 on 2026-10-01 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0001_initial"),
        ("help_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="help_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="help_requests.helprequest",
            ),
        ),
    ]
