# Generated by Django 5.2.17 on 2026-10-01 22:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0002_initial"),
        ("help_requests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "блокування",
                "verbose_name_plural": "блокування",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SPAM", "Спам"),
                            ("FRAUD", "Шахрайство"),
                            ("HARASSMENT", "Переслідування"),
                            ("DANGEROUS", "Небезпечно"),
                            ("INAPPROPRIATE", "Неприйнятний вміст"),
                            ("OTHER", "Інше"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Відкрита"),
                            ("IN_REVIEW", "Розглядається"),
                            ("RESOLVED", "Вирішена"),
                            ("DISMISSED", "Відхилена"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("moderator_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "help_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="help_requests.helprequest",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="conversations.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "скарга",
                "verbose_name_plural": "скарги",
                "ordering": ["-created_at"],
            },
        ),
    ]
