# Generated by Django 5.2.17 on 2026-10-01 22:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("help_requests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpResponse",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Очікує"),
                            ("ACCEPTED", "Прийнято"),
                            ("REJECTED", "Відхилено"),
                            ("CANCELLED", "Скасовано"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "help_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="help_requests.helprequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "відгук",
                "verbose_name_plural": "відгуки",
                "ordering": ["created_at"],
            },
        ),
    ]
