# Generated by Django 5.2.17 on 2026-10-01 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="helpresponse",
            name="helper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="help_responses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="helpresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "ACCEPTED"])),
                fields=("help_request", "helper"),
                name="unique_active_response_per_user_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="helpresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACCEPTED")),
                fields=("help_request",),
                name="single_accepted_response_per_request",
            ),
        ),
    ]
