# Generated by Django 5.2.17 on 2026-10-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpresponse",
            name="offer_type",
            field=models.CharField(
                choices=[
                    ("ACCEPT", "Згоден(-на) на умови автора"),
                    ("COUNTER", "Пропоную іншу суму"),
                    ("FREE", "Допоможу без оплати"),
                ],
                default="ACCEPT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="helpresponse",
            name="offered_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
