# Generated by Django 5.2.17 on 2026-10-07 14:42

from django.db import migrations, models


def copy_agreed_terms(apps, schema_editor):
    """Terms used to live on the request (one helper); move them to the accepted response."""
    HelpResponse = apps.get_model("interactions", "HelpResponse")
    for response in HelpResponse.objects.filter(status="ACCEPTED").select_related("help_request"):
        response.agreed_offer_type = response.help_request.agreed_offer_type
        response.agreed_amount = response.help_request.agreed_amount
        response.save(update_fields=["agreed_offer_type", "agreed_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_reward_offers"),
        ("help_requests", "0007_helprequest_helpers_needed"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="helpresponse",
            name="single_accepted_response_per_request",
        ),
        migrations.AddField(
            model_name="helpresponse",
            name="agreed_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="helpresponse",
            name="agreed_offer_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="helpresponse",
            name="author_counter_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(copy_agreed_terms, migrations.RunPython.noop),
    ]
