# Generated by Django 5.2.17 on 2026-10-01 22:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("AVATAR", "Аватар"), ("HELP_REQUEST", "Фото запиту"), ("CHAT", "Фото в чаті")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Очікує завантаження"), ("READY", "Готово"), ("FAILED", "Помилка")],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("declared_content_type", models.CharField(max_length=50)),
                ("declared_size", models.PositiveIntegerField()),
                ("original_key", models.CharField(max_length=255)),
                ("key", models.CharField(blank=True, max_length=255)),
                ("thumbnail_key", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=50)),
                ("size", models.PositiveIntegerField(blank=True, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("is_attached", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "медіафайл",
                "verbose_name_plural": "медіафайли",
            },
        ),
    ]
