# Generated by Django 5.2.17 on 2026-10-01 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="media", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["status", "is_attached", "created_at"], name="media_media_status_0d4d0d_idx"),
        ),
    ]
