# Generated by Django 5.2.17 on 2026-10-01 22:33

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="availability",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
                ),
                ("radius", models.PositiveIntegerField(default=3000)),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20), blank=True, default=list, size=None
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "доступність",
                "verbose_name_plural": "доступність",
                "indexes": [
                    models.Index(fields=["is_active", "expires_at"], name="locations_a_is_acti_b68f2e_idx"),
                    models.Index(fields=["location"], name="availability_location_gist"),
                ],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("country_code", models.CharField(max_length=2)),
                ("center", django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ("default_zoom", models.PositiveSmallIntegerField(default=12)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "місто",
                "verbose_name_plural": "міста",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)), fields=("is_default",), name="single_default_city"
                    )
                ],
            },
        ),
    ]
