# Generated by Django 5.2.17 on 2026-10-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_seed_lviv"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="translations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
