# Generated by Django 5.2.17 on 2026-10-01 22:33

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThankYou",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "подяка",
                "verbose_name_plural": "подяки",
                "ordering": ["-created_at"],
            },
        ),
    ]
