# Generated by Django 5.2.17 on 2026-10-01 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("help_requests", "0002_initial"),
        ("reputation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="thankyou",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="given_thanks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="thankyou",
            name="help_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="thanks", to="help_requests.helprequest"
            ),
        ),
        migrations.AddField(
            model_name="thankyou",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="received_thanks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="thankyou",
            constraint=models.UniqueConstraint(fields=("help_request",), name="unique_thank_you_per_request"),
        ),
    ]
