# Generated by Django 5.2.17 on 2026-10-07 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_requests", "0007_helprequest_helpers_needed"),
        ("reputation", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="thankyou",
            name="unique_thank_you_per_request",
        ),
        migrations.AddConstraint(
            model_name="thankyou",
            constraint=models.UniqueConstraint(fields=("help_request", "to_user"), name="unique_thank_you_per_helper"),
        ),
    ]
