# Generated by Django 5.2.17 on 2026-10-01 22:33

import django.contrib.gis.db.models.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HelpRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AUTO", "Автомобіль"),
                            ("HOME", "Дім"),
                            ("ITEMS", "Речі"),
                            ("ANIMALS", "Тварини"),
                            ("PEOPLE", "Людина"),
                            ("DISTRICT", "Район"),
                            ("URGENT", "Терміново"),
                            ("OTHER", "Інше"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("subcategory", models.CharField(blank=True, max_length=40, null=True)),
                ("title", models.CharField(max_length=120)),
                (
                    "description",
                    models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)]),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ("location_accuracy", models.FloatField(blank=True, null=True)),
                (
                    "urgency",
                    models.CharField(
                        choices=[("NOW", "Зараз"), ("TODAY", "Сьогодні"), ("WHENEVER", "Коли буде можливість")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[("NONE", "Просто допомога"), ("WILLING", "Готовий віддячити"), ("UNSURE", "Не знаю")],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "reward_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Активний"),
                            ("IN_PROGRESS", "Виконується"),
                            ("COMPLETED", "Завершено"),
                            ("CANCELLED", "Скасовано"),
                            ("EXPIRED", "Термін минув"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("in_progress_at", models.DateTimeField(blank=True, null=True)),
                ("first_response_at", models.DateTimeField(blank=True, null=True)),
                ("expiring_notified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "запит про допомогу",
                "verbose_name_plural": "запити про допомогу",
                "ordering": ["-created_at"],
            },
        ),
    ]
