# Generated by Django 5.2.17 on 2026-10-01 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("help_requests", "0001_initial"),
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="helprequest",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="help_requests", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="helprequest",
            name="photos",
            field=models.ManyToManyField(blank=True, related_name="+", to="media.media"),
        ),
        migrations.AddField(
            model_name="helprequest",
            name="selected_helper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="helped_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="helprequest",
            index=models.Index(fields=["status", "expires_at"], name="hr_status_expires_idx"),
        ),
        migrations.AddIndex(
            model_name="helprequest",
            index=models.Index(fields=["author", "status"], name="hr_author_status_idx"),
        ),
        migrations.AddIndex(
            model_name="helprequest",
            index=models.Index(fields=["selected_helper", "status"], name="hr_helper_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="helprequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("reward_amount__isnull", True), ("reward_amount__gte", 0), _connector="OR"),
                name="hr_reward_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="helprequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ["IN_PROGRESS", "COMPLETED"]), _negated=True),
                    ("selected_helper__isnull", False),
                    _connector="OR",
                ),
                name="hr_in_progress_has_helper",
            ),
        ),
    ]
