# Generated by Django 5.2.17 on 2026-10-02 23:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_requests", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="helprequest",
            name="agreed_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="helprequest",
            name="agreed_offer_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="helprequest",
            name="reward_options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("PIZZA", "Поставлю піцу"),
                        ("COFFEE", "Кава"),
                        ("RETURN_HELP", "Допоможу у відповідь"),
                        ("GIVE_ITEM", "Віддам/позичу річ"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
