# Generated by Django 5.2.17 on 2026-10-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_requests", "0004_share_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="helprequest",
            name="place_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="helprequest",
            name="reward_currency",
            field=models.CharField(default="UAH", max_length=3),
        ),
    ]
