# Generated by Django 5.2.17 on 2026-10-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_requests", "0005_place_and_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="helprequest",
            name="needed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="helprequest",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("NOW", "Зараз"),
                    ("TODAY", "Сьогодні"),
                    ("WHENEVER", "Коли буде можливість"),
                    ("SCHEDULED", "У визначений час"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
