# Generated by Django 5.2.17 on 2026-10-07 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_requests", "0006_scheduled_urgency"),
    ]

    operations = [
        migrations.AddField(
            model_name="helprequest",
            name="helpers_needed",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
            ),
        ),
    ]
